import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { Inter } from "next/font/google";
import Providers from "./state/services/providers";
import theme from "./styles/theme";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta property="og:image" content="favicon.ico" />
      <meta name="title" content="Music app" />
      <meta property="og:title" content="Music app" />
      <meta property="og:type" content="website" />
      <meta
        property="og:url"
        content="https://react-music-app-liart.vercel.app/"
      />

      <body style={{ background: "#F9FAFE" }}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
